CREATE TABLE TARIFAS (
	ID_TARIFA INT PRIMARY KEY NOT NULL,
	NOMBRE_T VARCHAR(25),
	VALOR INT
);

CREATE TABLE SECTOR (
	ID_S INT PRIMARY KEY NOT NULL,
	COORD_INICIO INT,
	COORD_FIN INT,
	DIST_RECORRIDO INT,
	NOMBRE_CIUDAD VARCHAR(25),
	REGION INT,
	ID_TARIFA INT,
	CONSTRAINT FK_ID_TARIFA_SECTOR FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA) ON DELETE SET NULL
);



CREATE TABLE NORMAL (
	ID_TARIFA INT,
	ASIENTOS INT,
	PUERTAS INT,
	CONSTRAINT FK_ID_TARIFA_NORMAL FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);

CREATE TABLE DISCAPACIDAD (
	ID_TARIFA INT,
	TIPO VARCHAR(25),
	PALANCA BIT,
	CONSTRAINT FK_ID_TARIFA_DISCAPACIDAD FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);

CREATE TABLE DEPORTIVO (
	ID_TARIFA INT,
	PARRILLA BIT,
	CARRO BIT,
	CONSTRAINT FK_ID_TARIFA_DEPORTIVO FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);

CREATE TABLE DIA (
	ID_TARIFA INT,
	HORA TIME,
	RIESGO VARCHAR(25),
	LLUVIA BIT,
	CONSTRAINT FK_ID_TARIFA_DIA FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);

CREATE TABLE TARDE (
	ID_TARIFA INT,
	TEMPORADA VARCHAR(25),
	CONGESTION BIT,
	NIEVE BIT,
	CONSTRAINT FK_ID_TARIFA_TARDE FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);

CREATE TABLE NOCHE (
	ID_TARIFA INT,
	RIESGO BIT,
	GRUPO BIT,
	FEESTIVO BIT,
	CONSTRAINT FK_ID_TARIFA_NOCHE FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);

CREATE TABLE AMANECIDA (
	ID_TARIFA INT,
	AEROPUERTO BIT,
	TRAFICO BIT,
	MALETAS BIT,
	CONSTRAINT FK_ID_TARIFA_AMANECIDA FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(ID_TARIFA)
);